name: CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macOS-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use a specific JDK distribution
          java-version: '11'
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run intl_utils:generate
      - run: flutter build ios --release --no-codesign --suppress-analytics

  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use a specific JDK distribution
          java-version: '11'
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ' 3.22.3'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run intl_utils:generate
      - run: flutter build apk --release